<select id="countryslux" size="1" onchange="fetch_inst();">
<option value='' selected='selected'>(choose country)</option>
<option value='w_af'>Afghanistan</option>
<option value='w_al'>Albania</option>
<option value='w_dz'>Algeria</option>
<option value='w_ad'>Andorra</option>
<option value='w_ao'>Angola</option>
<option value='w_ag'>Antigua and Barbuda</option>
<option value='w_ar'>Argentina</option>
<option value='w_am'>Armenia</option>
<option value='w_aw'>Aruba</option>
<option value='w_au'>Australia</option>
<option value='w_at'>Austria</option>
<option value='w_az'>Azerbaijan</option>
<option value='w_bs'>Bahamas</option>
<option value='w_bh'>Bahrain</option>
<option value='w_bd'>Bangladesh</option>
<option value='w_bb'>Barbados</option>
<option value='w_by'>Belarus</option>
<option value='w_be'>Belgium</option>
<option value='w_bz'>Belize</option>
<option value='w_bj'>Benin</option>
<option value='w_bm'>Bermuda</option>
<option value='w_bt'>Bhutan</option>
<option value='w_bo'>Bolivia</option>
<option value='w_ba'>Bosnia and Herzegovina</option>
<option value='w_bw'>Botswana</option>
<option value='w_br'>Brazil</option>
<option value='w_vg'>British Virgin Islands</option>
<option value='w_bn'>Brunei</option>
<option value='w_bg'>Bulgaria</option>
<option value='w_bf'>Burkina Faso</option>
<option value='w_bi'>Burundi</option>
<option value='w_kh'>Cambodia</option>
<option value='w_cm'>Cameroon</option>
<option value='w_ca'>Canada</option>
<option value='w_cv'>Cape Verde</option>
<option value='w_ky'>Cayman Islands</option>
<option value='w_cf'>Central African Republic</option>
<option value='w_td'>Chad</option>
<option value='w_cl'>Chile</option>
<option value='w_cn'>China</option>
<option value='w_co'>Colombia</option>
<option value='w_cr'>Costa Rica</option>
<option value='w_ci'>Cote d’Ivoire</option>
<option value='w_hr'>Croatia</option>
<option value='w_cu'>Cuba</option>
<option value='w_cy'>Cyprus</option>
<option value='w_cz'>Czech Republic</option>
<option value='w_cd'>Democratic Republic of the Congo</option>
<option value='w_dk'>Denmark</option>
<option value='w_dj'>Djibouti</option>
<option value='w_dm'>Dominica</option>
<option value='w_do'>Dominican Republic</option>
<option value='w_tl'>East Timor</option>
<option value='w_ec'>Ecuador</option>
<option value='w_eg'>Egypt</option>
<option value='w_sv'>El Salvador</option>
<option value='w_er'>Eritrea</option>
<option value='w_ee'>Estonia</option>
<option value='w_et'>Ethiopia</option>
<option value='w_eu'>Europe-wide</option>
<option value='w_fo'>Faroe Islands</option>
<option value='w_fj'>Fiji</option>
<option value='w_fi'>Finland</option>
<option value='w_fr'>France</option>
<option value='w_pf'>French Polynesia</option>
<option value='w_ga'>Gabon</option>
<option value='w_gm'>Gambia</option>
<option value='w_ge'>Georgia</option>
<option value='w_de'>Germany</option>
<option value='w_gh'>Ghana</option>
<option value='w_gr'>Greece</option>
<option value='w_gl'>Greenland</option>
<option value='w_gd'>Grenada</option>
<option value='w_gu'>Guam</option>
<option value='w_gt'>Guatemala</option>
<option value='w_gn'>Guinea</option>
<option value='w_gy'>Guyana</option>
<option value='w_ht'>Haiti</option>
<option value='w_hn'>Honduras</option>
<option value='w_hk'>Hong Kong</option>
<option value='w_hu'>Hungary</option>
<option value='w_is'>Iceland</option>
<option value='w_in'>India</option>
<option value='w_id'>Indonesia</option>
<option value='w_ir'>Iran</option>
<option value='w_iq'>Iraq</option>
<option value='w_ie'>Ireland</option>
<option value='w_im'>Isle of Man</option>
<option value='w_il'>Israel</option>
<option value='w_it'>Italy</option>
<option value='w_jm'>Jamaica</option>
<option value='w_jp'>Japan</option>
<option value='w_jo'>Jordan</option>
<option value='w_kz'>Kazakstan</option>
<option value='w_ke'>Kenya</option>
<option value='w_kr'>Korea Republic</option>
<option value='w_kw'>Kuwait</option>
<option value='w_kg'>Kyrgyzstan</option>
<option value='w_la'>Lao People’s Democratic Republic</option>
<option value='w_lv'>Latvia</option>
<option value='w_lb'>Lebanon</option>
<option value='w_ls'>Lesotho</option>
<option value='w_lr'>Liberia</option>
<option value='w_ly'>Libya</option>
<option value='w_li'>Liechtenstein</option>
<option value='w_lt'>Lithuania</option>
<option value='w_lu'>Luxembourg</option>
<option value='w_mo'>Macau</option>
<option value='w_mk'>Macedonia</option>
<option value='w_mg'>Madagascar</option>
<option value='w_mw'>Malawi</option>
<option value='w_my'>Malaysia</option>
<option value='w_mv'>Maldives</option>
<option value='w_ml'>Mali</option>
<option value='w_mt'>Malta</option>
<option value='w_mh'>Marshall Islands</option>
<option value='w_mt'>Marshall Islands</option>
<option value='w_mr'>Mauritania</option>
<option value='w_mu'>Mauritius</option>
<option value='w_mx'>Mexico</option>
<option value='w_fm'>Micronesia</option>
<option value='w_md'>Moldova</option>
<option value='w_mc'>Monaco</option>
<option value='w_mn'>Mongolia</option>
<option value='w_me'>Montenegro</option>
<option value='w_ma'>Morocco</option>
<option value='w_mz'>Mozambique</option>
<option value='w_xx'>Multinational</option>
<option value='w_mm'>Myanmar</option>
<option value='w_na'>Namibia</option>
<option value='w_np'>Nepal</option>
<option value='w_nl'>Netherlands</option>
<option value='w_an'>Netherlands Antilles</option>
<option value='w_nc'>New Caledonia</option>
<option value='w_nz'>New Zealand</option>
<option value='w_ni'>Nicaragua</option>
<option value='w_ne'>Niger</option>
<option value='w_ng'>Nigeria</option>
<option value='w_nu'>Niue Islands</option>
<option value='w_mp'>Northern Mariana Islands</option>
<option value='w_no'>Norway</option>
<option value='w_om'>Oman</option>
<option value='w_pk'>Pakistan</option>
<option value='w_ps'>Palestine</option>
<option value='w_pa'>Panama</option>
<option value='w_pg'>Papua New Guinea</option>
<option value='w_py'>Paraguay</option>
<option value='w_pe'>Peru</option>
<option value='w_ph'>Philippines</option>
<option value='w_pl'>Poland</option>
<option value='w_pt'>Portugal</option>
<option value='w_pr'>Puerto Rico</option>
<option value='w_qa'>Qatar</option>
<option value='w_cg'>Republic of the Congo</option>
<option value='w_ro'>Romania</option>
<option value='w_ru'>Russian Federation</option>
<option value='w_rw'>Rwanda</option>
<option value='w_kn'>Saint Kitts and Nevis</option>
<option value='w_sm'>San Marino</option>
<option value='w_sa'>Saudi Arabia</option>
<option value='w_sn'>Senegal</option>
<option value='w_rs'>Serbia</option>
<option value='w_sl'>Sierra Leone</option>
<option value='w_sg'>Singapore</option>
<option value='w_sk'>Slovak Republic</option>
<option value='w_si'>Slovenia</option>
<option value='w_sb'>Solomon Islands</option>
<option value='w_so'>Somalia</option>
<option value='w_za'>South Africa</option>
<option value='w_es'>Spain</option>
<option value='w_lk'>Sri Lanka</option>
<option value='w_sd'>Sudan</option>
<option value='w_sr'>Suriname</option>
<option value='w_sz'>Swaziland</option>
<option value='w_se'>Sweden</option>
<option value='w_ch'>Switzerland</option>
<option value='w_sy'>Syria</option>
<option value='w_tw'>Taiwan</option>
<option value='w_tj'>Tajikistan</option>
<option value='w_tz'>Tanzania</option>
<option value='w_th'>Thailand</option>
<option value='w_tg'>Togo</option>
<option value='w_to'>Tonga</option>
<option value='w_tt'>Trinidad and Tobago</option>
<option value='w_tn'>Tunisia</option>
<option value='w_tr'>Turkey</option>
<option value='w_ty'>Turkish Cyprus</option>
<option value='w_tm'>Turkmenistan</option>
<option value='w_tc'>Turks and Caicos Islands</option>
<option value='u_al'>Alabama</option>
<option value='u_ak'>US Alaska</option>
<option value='u_az'>US Arizona</option>
<option value='u_ar'>US Arkansas</option>
<option value='u_ca'>US California</option>
<option value='u_co'>US Colorado</option>
<option value='u_ct'>US Connecticut</option>
<option value='u_de'>US Delaware</option>
<option value='u_dc'>US District of Columbia</option>
<option value='u_fl'>US Florida</option>
<option value='u_ga'>US Georgia</option>
<option value='u_hi'>US Hawaii</option>
<option value='u_id'>US Idaho</option>
<option value='u_il'>US Illinois</option>
<option value='u_in'>US Indiana</option>
<option value='u_ia'>US Iowa</option>
<option value='u_ks'>US Kansas</option>
<option value='u_ky'>US Kentucky</option>
<option value='u_la'>US Louisiana</option>
<option value='u_me'>US Maine</option>
<option value='u_md'>US Maryland</option>
<option value='u_ma'>US Massachusetts</option>
<option value='u_mi'>US Michigan</option>
<option value='u_mn'>US Minnesota</option>
<option value='u_ms'>US Mississippi</option>
<option value='u_mo'>US Missouri</option>
<option value='u_mt'>US Montana</option>
<option value='u_ne'>US Nebraska</option>
<option value='u_nv'>US Nevada</option>
<option value='u_nh'>US New Hampshire</option>
<option value='u_nj'>US New Jersey</option>
<option value='u_nm'>US New Mexico</option>
<option value='u_ny'>US New York</option>
<option value='u_nc'>US North Carolina</option>
<option value='u_nd'>US North Dakota</option>
<option value='u_oh'>US Ohio</option>
<option value='u_ok'>US Oklahoma</option>
<option value='u_or'>US Oregon</option>
<option value='u_pa'>US Pennsylvania</option>
<option value='u_ri'>US Rhode Island</option>
<option value='u_sc'>US South Carolina</option>
<option value='u_sd'>US South Dakota</option>
<option value='u_tn'>US Tennessee</option>
<option value='u_tx'>US Texas</option>
<option value='u_ut'>US Utah</option>
<option value='u_vt'>US Vermont</option>
<option value='u_va'>US Virginia</option>
<option value='u_wa'>US Washington</option>
<option value='u_wv'>US West Virginia</option>
<option value='u_wi'>US Wisconsin</option>
<option value='u_wy'>US Wyoming</option>
<option value='w_us'>U.S.A.</option>
<option value='w_vi'>US Virgin Islands</option>
<option value='w_ug'>Uganda</option>
<option value='w_ua'>Ukraine</option>
<option value='w_ae'>United Arab Emirates</option>
<option value='w_uk'>United Kingdom</option>
<option value='w_uy'>Uruguay</option>
<option value='w_uz'>Uzbekistan</option>
<option value='w_va'>Vatican</option>
<option value='w_ve'>Venezuela</option>
<option value='w_vn'>Vietnam</option>
<option value='w_ws'>Western Samoa</option>
<option value='w_ye'>Yemen</option>
<option value='w_zm'>Zambia</option>
<option value='w_zw'>Zimbabwe</option>
</select>
